# ===============================
# = Hibernate datasource
# ===============================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/karetis_project?useUnicode=true
      &useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&
      serverTimezone=UTC
    username: root
    password:

  # ===============================
  # = JPA configurations
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc:
          batch_size: 5

# ===============================
# = Hibernate configurations
# ===============================




